// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMgBkETXcuyCsMNoSI_OD3vv88OcaqiFk',
    appId: '1:810992651230:web:657039d6beb90667fdab4f',
    messagingSenderId: '810992651230',
    projectId: 'fir-flutter-codelab-b3e96',
    authDomain: 'fir-flutter-codelab-b3e96.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b3e96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kCoi6qXPJxWsAAx4PGWuV7iyKSepGGM',
    appId: '1:810992651230:android:acbd08bfddfcb7cefdab4f',
    messagingSenderId: '810992651230',
    projectId: 'fir-flutter-codelab-b3e96',
    storageBucket: 'fir-flutter-codelab-b3e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnz0QnZJ-f8jR1kQHKgAco-PgkxvT1u4A',
    appId: '1:810992651230:ios:0237d15282a0f0fafdab4f',
    messagingSenderId: '810992651230',
    projectId: 'fir-flutter-codelab-b3e96',
    storageBucket: 'fir-flutter-codelab-b3e96.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnz0QnZJ-f8jR1kQHKgAco-PgkxvT1u4A',
    appId: '1:810992651230:ios:0237d15282a0f0fafdab4f',
    messagingSenderId: '810992651230',
    projectId: 'fir-flutter-codelab-b3e96',
    storageBucket: 'fir-flutter-codelab-b3e96.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
